# Generated by Django 5.1.4 on 2024-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_notifications_alter_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
